'use client'

import { Inter } from "next/font/google";
import Link from "next/link";
import './layout.css'
import { Router } from "next/router";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter()
  return (
    <html lang="en">
      <body>
       <div className="nav-container">
        <Link href={'/'}>Main</Link>
        <ul>
          <button onClick={() => router.push('/about')}>About</button>
          <li>My family</li>
          <li>My hobbies</li>
          <li>My work</li>
          <li>My studies</li>
        </ul>
       </div>
        {children}
        <div className="footer-container">
          <Link href={'/'}>In addition</Link>
          <ul>
            <li>Contact</li>
            <li>Blog</li>
            <li>Help</li>
          </ul>
      
        </div>
        </body>
    </html>
  );
}
